### ISSUE TITLE
Won't compile with openssl-1.1+

### ISSUE THREAD

**Issue by ghost** [ArchiveTeam/wget-lua-og#7]
```
       ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from openssl.c:39:
/usr/include/openssl/ssl.h:1626:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void)) /* TLSv1.0 */
 ^
openssl.c: In function 'ssl_connect_wget':
openssl.c:428:38: error: dereferencing pointer to incomplete type 'SSL {aka struct ssl_st}'
   if (SSL_connect (conn) <= 0 || conn->state != SSL_ST_OK)
                                      ^~
openssl.c:428:49: error: 'SSL_ST_OK' undeclared (first use in this function); did you mean 'TLS_ST_OK'?
   if (SSL_connect (conn) <= 0 || conn->state != SSL_ST_OK)
                                                 ^~~~~~~~~
                                                 TLS_ST_OK
openssl.c:428:49: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1525: recipe for target 'openssl.o' failed
make[3]: *** [openssl.o] Error 1
make[3]: Leaving directory '/root/tumblr-grab-master/get-wget-lua.tmp/src'
Makefile:1344: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/tumblr-grab-master/get-wget-lua.tmp/src'
Makefile:1355: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/tumblr-grab-master/get-wget-lua.tmp'
Makefile:1311: recipe for target 'all' failed
make: *** [all] Error 2

```

Which makes building on Ubuntu 18.04 difficult without switching to gnutls.

Looks like we either need to patch wget-lua for newer distros or recommend/require gnutls.
